### ISSUE TITLE
TLS Error When Performing SNMP write calls

### ISSUE THREAD

**Issue by VictorRascol** [jbemmel/srl-snmp-set#1]
After installing the agent per Nokia documentation; when attempting to send snmp write calls, the agent returns a success message but the request does not actually get applied.

When looking at the logs on the switch in question, I see the following entry.

###TIMESTAMP HOSTNAME### sr_gnmi_server: debug|3217|296824|00002|W: gnmi_grpc ssl_transport_security.cc:1233     SrlGrpcLog  Handshake failed with fatal error SSL_ERROR_SSL: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate.

Any ideas?

**Comment by jbemmel** [comment]
Thanks for reaching out

Could you elaborate on your setup? Which SRL version are you using, and is this a physical or virtual box?

It sounds like you may be deploying the agent on a physical switch, as opposed to the virtual containerlab setup provided in this repo. If so, my guess would be that https://github.com/jbemmel/srl-snmp-set/blob/main/src/snmp-set/scripts/gnmic-set-ifstatus.sh#L6 may need to be adjusted; perhaps @karimra could comment

Regarding the virtual setup in this repo, I had to make some adjustments to accommodate SRL 21.11. Perhaps you could validate if you can deploy the updated lab, and use the documented snmpset CLI commands to change the status of the lo0 interface? If that works, then we can compare the virtual configs with the "real" setup and identify any deltas

**Comment by jbemmel** [comment]
For reference, this is the gNMI configuration that ends up being applied to the virtual containers (SRL 21.11.1):
```
--{ + running }--[ system gnmi-server ]--
A:spine1# info detail
    admin-state enable
    timeout 7200
    rate-limit 60
    session-limit 20
    commit-confirmed-timeout 0
    commit-save false
    include-defaults-in-config-only-responses false
    network-instance mgmt {
        admin-state enable
        use-authentication true
        port 57400
        tls-profile clab-profile
    }
    unix-socket {
        admin-state disable
        use-authentication true
    }
```

The TLS details are under /system/tls, 'authenticate-client' is set to 'false' there. If that is configured as 'true', the gnmic command referenced above would have to be changed to send a certificate

For production deployments, the gNMI communication could be modified to use a Unix socket instead (since it is local anyway), this would be more secure and could potentially side-step the certificate issue; let me know if you'd like me to update the example to do it that way

**Comment by VictorRascol** [comment]
Thank you for your feedback! I would love to see an example of how to implement unix socket communication.

the 'authenticate-client' configuration value in /system/tls set to false fixed the issue!

This was tested on a physical D1 7220 on software version v21.6.3.
I will confirm that it's working on the latest v21.11.1 as well.

**Comment by jbemmel** [comment]
This issue did highlight some missing error handling, so I added it: https://github.com/jbemmel/srl-snmp-set/blob/main/src/snmp-set/scripts/snmp_write_handler.pl#L24

Glad it worked out

**Comment by jbemmel** [comment]
> Thank you for your feedback! I would love to see an example of how to implement unix socket communication.

See https://github.com/jbemmel/srl-snmp-set/commit/ee182cf51eda5cd1c39f8bab248f7f91b9f3c226, updated to use a Unix socket instead
