### ISSUE TITLE
SNMP Service Restart Fails by Default

### ISSUE THREAD

**Issue by VictorRascol** [jbemmel/srl-snmp-set#2]
https://github.com/jbemmel/srl-snmp-set/blob/ee182cf51eda5cd1c39f8bab248f7f91b9f3c226/src/snmp-set/snmp-set-agent.py#L113

By using awk '/\/usr\/sbin\/snmpd/ {{print $4}}' to get PID, the script assumes that the snmpd service is running (which is not the case by default). The snmp service is snmp_server on 21.x.x and sr_snmp_server on 22.x.x. This results in the running snmp service not getting restarted. It seems this was added in order to not match the grep process in the ps output.

Recommend doing something like this instead.

`/usr/bin/ps -AlF | grep {conf_file} | grep -v grep | awk '{{print $4}}' | xargs kill -9
`

Tested and still working on v22.3.1 with this change.

**Comment by jbemmel** [comment]
Applied in https://github.com/jbemmel/srl-snmp-set/commit/f9963803e9cddf8f728eda4b83f8934d9ed8e661, thanks
